# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.25

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/vboxuser/Documents/SeniorDesignProject/xmr-prototype-testing-schema-loading

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/vboxuser/Documents/SeniorDesignProject/xmr-prototype-testing-schema-loading

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\" \"development\" \"gmock\" \"gtest\" \"runtime\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/vboxuser/Documents/SeniorDesignProject/xmr-prototype-testing-schema-loading/CMakeFiles /home/vboxuser/Documents/SeniorDesignProject/xmr-prototype-testing-schema-loading//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/vboxuser/Documents/SeniorDesignProject/xmr-prototype-testing-schema-loading/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named XMR

# Build rule for target.
XMR: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 XMR
.PHONY : XMR

# fast build rule for target.
XMR/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/XMR.dir/build.make CMakeFiles/XMR.dir/build
.PHONY : XMR/fast

#=============================================================================
# Target rules for targets named doc-xml

# Build rule for target.
doc-xml: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 doc-xml
.PHONY : doc-xml

# fast build rule for target.
doc-xml/fast:
	$(MAKE) $(MAKESILENT) -f _deps/xerces-c-build/doc/CMakeFiles/doc-xml.dir/build.make _deps/xerces-c-build/doc/CMakeFiles/doc-xml.dir/build
.PHONY : doc-xml/fast

#=============================================================================
# Target rules for targets named doc-style

# Build rule for target.
doc-style: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 doc-style
.PHONY : doc-style

# fast build rule for target.
doc-style/fast:
	$(MAKE) $(MAKESILENT) -f _deps/xerces-c-build/doc/CMakeFiles/doc-style.dir/build.make _deps/xerces-c-build/doc/CMakeFiles/doc-style.dir/build
.PHONY : doc-style/fast

#=============================================================================
# Target rules for targets named xerces-c-missing

# Build rule for target.
xerces-c-missing: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 xerces-c-missing
.PHONY : xerces-c-missing

# fast build rule for target.
xerces-c-missing/fast:
	$(MAKE) $(MAKESILENT) -f _deps/xerces-c-build/src/CMakeFiles/xerces-c-missing.dir/build.make _deps/xerces-c-build/src/CMakeFiles/xerces-c-missing.dir/build
.PHONY : xerces-c-missing/fast

#=============================================================================
# Target rules for targets named xerces-c-headers

# Build rule for target.
xerces-c-headers: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 xerces-c-headers
.PHONY : xerces-c-headers

# fast build rule for target.
xerces-c-headers/fast:
	$(MAKE) $(MAKESILENT) -f _deps/xerces-c-build/src/CMakeFiles/xerces-c-headers.dir/build.make _deps/xerces-c-build/src/CMakeFiles/xerces-c-headers.dir/build
.PHONY : xerces-c-headers/fast

#=============================================================================
# Target rules for targets named xerces-c

# Build rule for target.
xerces-c: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 xerces-c
.PHONY : xerces-c

# fast build rule for target.
xerces-c/fast:
	$(MAKE) $(MAKESILENT) -f _deps/xerces-c-build/src/CMakeFiles/xerces-c.dir/build.make _deps/xerces-c-build/src/CMakeFiles/xerces-c.dir/build
.PHONY : xerces-c/fast

#=============================================================================
# Target rules for targets named DOMTest

# Build rule for target.
DOMTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 DOMTest
.PHONY : DOMTest

# fast build rule for target.
DOMTest/fast:
	$(MAKE) $(MAKESILENT) -f _deps/xerces-c-build/tests/CMakeFiles/DOMTest.dir/build.make _deps/xerces-c-build/tests/CMakeFiles/DOMTest.dir/build
.PHONY : DOMTest/fast

#=============================================================================
# Target rules for targets named DOMMemTest

# Build rule for target.
DOMMemTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 DOMMemTest
.PHONY : DOMMemTest

# fast build rule for target.
DOMMemTest/fast:
	$(MAKE) $(MAKESILENT) -f _deps/xerces-c-build/tests/CMakeFiles/DOMMemTest.dir/build.make _deps/xerces-c-build/tests/CMakeFiles/DOMMemTest.dir/build
.PHONY : DOMMemTest/fast

#=============================================================================
# Target rules for targets named Normalizer

# Build rule for target.
Normalizer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Normalizer
.PHONY : Normalizer

# fast build rule for target.
Normalizer/fast:
	$(MAKE) $(MAKESILENT) -f _deps/xerces-c-build/tests/CMakeFiles/Normalizer.dir/build.make _deps/xerces-c-build/tests/CMakeFiles/Normalizer.dir/build
.PHONY : Normalizer/fast

#=============================================================================
# Target rules for targets named RangeTest

# Build rule for target.
RangeTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 RangeTest
.PHONY : RangeTest

# fast build rule for target.
RangeTest/fast:
	$(MAKE) $(MAKESILENT) -f _deps/xerces-c-build/tests/CMakeFiles/RangeTest.dir/build.make _deps/xerces-c-build/tests/CMakeFiles/RangeTest.dir/build
.PHONY : RangeTest/fast

#=============================================================================
# Target rules for targets named DOMTraversalTest

# Build rule for target.
DOMTraversalTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 DOMTraversalTest
.PHONY : DOMTraversalTest

# fast build rule for target.
DOMTraversalTest/fast:
	$(MAKE) $(MAKESILENT) -f _deps/xerces-c-build/tests/CMakeFiles/DOMTraversalTest.dir/build.make _deps/xerces-c-build/tests/CMakeFiles/DOMTraversalTest.dir/build
.PHONY : DOMTraversalTest/fast

#=============================================================================
# Target rules for targets named DOMTypeInfoTest

# Build rule for target.
DOMTypeInfoTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 DOMTypeInfoTest
.PHONY : DOMTypeInfoTest

# fast build rule for target.
DOMTypeInfoTest/fast:
	$(MAKE) $(MAKESILENT) -f _deps/xerces-c-build/tests/CMakeFiles/DOMTypeInfoTest.dir/build.make _deps/xerces-c-build/tests/CMakeFiles/DOMTypeInfoTest.dir/build
.PHONY : DOMTypeInfoTest/fast

#=============================================================================
# Target rules for targets named EncodingTest

# Build rule for target.
EncodingTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 EncodingTest
.PHONY : EncodingTest

# fast build rule for target.
EncodingTest/fast:
	$(MAKE) $(MAKESILENT) -f _deps/xerces-c-build/tests/CMakeFiles/EncodingTest.dir/build.make _deps/xerces-c-build/tests/CMakeFiles/EncodingTest.dir/build
.PHONY : EncodingTest/fast

#=============================================================================
# Target rules for targets named InitTermTest

# Build rule for target.
InitTermTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 InitTermTest
.PHONY : InitTermTest

# fast build rule for target.
InitTermTest/fast:
	$(MAKE) $(MAKESILENT) -f _deps/xerces-c-build/tests/CMakeFiles/InitTermTest.dir/build.make _deps/xerces-c-build/tests/CMakeFiles/InitTermTest.dir/build
.PHONY : InitTermTest/fast

#=============================================================================
# Target rules for targets named MemHandlerTest

# Build rule for target.
MemHandlerTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MemHandlerTest
.PHONY : MemHandlerTest

# fast build rule for target.
MemHandlerTest/fast:
	$(MAKE) $(MAKESILENT) -f _deps/xerces-c-build/tests/CMakeFiles/MemHandlerTest.dir/build.make _deps/xerces-c-build/tests/CMakeFiles/MemHandlerTest.dir/build
.PHONY : MemHandlerTest/fast

#=============================================================================
# Target rules for targets named NetAccessorTest

# Build rule for target.
NetAccessorTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NetAccessorTest
.PHONY : NetAccessorTest

# fast build rule for target.
NetAccessorTest/fast:
	$(MAKE) $(MAKESILENT) -f _deps/xerces-c-build/tests/CMakeFiles/NetAccessorTest.dir/build.make _deps/xerces-c-build/tests/CMakeFiles/NetAccessorTest.dir/build
.PHONY : NetAccessorTest/fast

#=============================================================================
# Target rules for targets named ThreadTest

# Build rule for target.
ThreadTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ThreadTest
.PHONY : ThreadTest

# fast build rule for target.
ThreadTest/fast:
	$(MAKE) $(MAKESILENT) -f _deps/xerces-c-build/tests/CMakeFiles/ThreadTest.dir/build.make _deps/xerces-c-build/tests/CMakeFiles/ThreadTest.dir/build
.PHONY : ThreadTest/fast

#=============================================================================
# Target rules for targets named XSerializerTest

# Build rule for target.
XSerializerTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 XSerializerTest
.PHONY : XSerializerTest

# fast build rule for target.
XSerializerTest/fast:
	$(MAKE) $(MAKESILENT) -f _deps/xerces-c-build/tests/CMakeFiles/XSerializerTest.dir/build.make _deps/xerces-c-build/tests/CMakeFiles/XSerializerTest.dir/build
.PHONY : XSerializerTest/fast

#=============================================================================
# Target rules for targets named XSTSHarness

# Build rule for target.
XSTSHarness: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 XSTSHarness
.PHONY : XSTSHarness

# fast build rule for target.
XSTSHarness/fast:
	$(MAKE) $(MAKESILENT) -f _deps/xerces-c-build/tests/CMakeFiles/XSTSHarness.dir/build.make _deps/xerces-c-build/tests/CMakeFiles/XSTSHarness.dir/build
.PHONY : XSTSHarness/fast

#=============================================================================
# Target rules for targets named XSValueTest

# Build rule for target.
XSValueTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 XSValueTest
.PHONY : XSValueTest

# fast build rule for target.
XSValueTest/fast:
	$(MAKE) $(MAKESILENT) -f _deps/xerces-c-build/tests/CMakeFiles/XSValueTest.dir/build.make _deps/xerces-c-build/tests/CMakeFiles/XSValueTest.dir/build
.PHONY : XSValueTest/fast

#=============================================================================
# Target rules for targets named Char16Test

# Build rule for target.
Char16Test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Char16Test
.PHONY : Char16Test

# fast build rule for target.
Char16Test/fast:
	$(MAKE) $(MAKESILENT) -f _deps/xerces-c-build/tests/CMakeFiles/Char16Test.dir/build.make _deps/xerces-c-build/tests/CMakeFiles/Char16Test.dir/build
.PHONY : Char16Test/fast

#=============================================================================
# Target rules for targets named CreateDOMDocument

# Build rule for target.
CreateDOMDocument: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 CreateDOMDocument
.PHONY : CreateDOMDocument

# fast build rule for target.
CreateDOMDocument/fast:
	$(MAKE) $(MAKESILENT) -f _deps/xerces-c-build/samples/CMakeFiles/CreateDOMDocument.dir/build.make _deps/xerces-c-build/samples/CMakeFiles/CreateDOMDocument.dir/build
.PHONY : CreateDOMDocument/fast

#=============================================================================
# Target rules for targets named DOMCount

# Build rule for target.
DOMCount: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 DOMCount
.PHONY : DOMCount

# fast build rule for target.
DOMCount/fast:
	$(MAKE) $(MAKESILENT) -f _deps/xerces-c-build/samples/CMakeFiles/DOMCount.dir/build.make _deps/xerces-c-build/samples/CMakeFiles/DOMCount.dir/build
.PHONY : DOMCount/fast

#=============================================================================
# Target rules for targets named DOMPrint

# Build rule for target.
DOMPrint: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 DOMPrint
.PHONY : DOMPrint

# fast build rule for target.
DOMPrint/fast:
	$(MAKE) $(MAKESILENT) -f _deps/xerces-c-build/samples/CMakeFiles/DOMPrint.dir/build.make _deps/xerces-c-build/samples/CMakeFiles/DOMPrint.dir/build
.PHONY : DOMPrint/fast

#=============================================================================
# Target rules for targets named EnumVal

# Build rule for target.
EnumVal: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 EnumVal
.PHONY : EnumVal

# fast build rule for target.
EnumVal/fast:
	$(MAKE) $(MAKESILENT) -f _deps/xerces-c-build/samples/CMakeFiles/EnumVal.dir/build.make _deps/xerces-c-build/samples/CMakeFiles/EnumVal.dir/build
.PHONY : EnumVal/fast

#=============================================================================
# Target rules for targets named MemParse

# Build rule for target.
MemParse: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MemParse
.PHONY : MemParse

# fast build rule for target.
MemParse/fast:
	$(MAKE) $(MAKESILENT) -f _deps/xerces-c-build/samples/CMakeFiles/MemParse.dir/build.make _deps/xerces-c-build/samples/CMakeFiles/MemParse.dir/build
.PHONY : MemParse/fast

#=============================================================================
# Target rules for targets named PParse

# Build rule for target.
PParse: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 PParse
.PHONY : PParse

# fast build rule for target.
PParse/fast:
	$(MAKE) $(MAKESILENT) -f _deps/xerces-c-build/samples/CMakeFiles/PParse.dir/build.make _deps/xerces-c-build/samples/CMakeFiles/PParse.dir/build
.PHONY : PParse/fast

#=============================================================================
# Target rules for targets named PSVIWriter

# Build rule for target.
PSVIWriter: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 PSVIWriter
.PHONY : PSVIWriter

# fast build rule for target.
PSVIWriter/fast:
	$(MAKE) $(MAKESILENT) -f _deps/xerces-c-build/samples/CMakeFiles/PSVIWriter.dir/build.make _deps/xerces-c-build/samples/CMakeFiles/PSVIWriter.dir/build
.PHONY : PSVIWriter/fast

#=============================================================================
# Target rules for targets named Redirect

# Build rule for target.
Redirect: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Redirect
.PHONY : Redirect

# fast build rule for target.
Redirect/fast:
	$(MAKE) $(MAKESILENT) -f _deps/xerces-c-build/samples/CMakeFiles/Redirect.dir/build.make _deps/xerces-c-build/samples/CMakeFiles/Redirect.dir/build
.PHONY : Redirect/fast

#=============================================================================
# Target rules for targets named SAX2Count

# Build rule for target.
SAX2Count: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SAX2Count
.PHONY : SAX2Count

# fast build rule for target.
SAX2Count/fast:
	$(MAKE) $(MAKESILENT) -f _deps/xerces-c-build/samples/CMakeFiles/SAX2Count.dir/build.make _deps/xerces-c-build/samples/CMakeFiles/SAX2Count.dir/build
.PHONY : SAX2Count/fast

#=============================================================================
# Target rules for targets named SAX2Print

# Build rule for target.
SAX2Print: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SAX2Print
.PHONY : SAX2Print

# fast build rule for target.
SAX2Print/fast:
	$(MAKE) $(MAKESILENT) -f _deps/xerces-c-build/samples/CMakeFiles/SAX2Print.dir/build.make _deps/xerces-c-build/samples/CMakeFiles/SAX2Print.dir/build
.PHONY : SAX2Print/fast

#=============================================================================
# Target rules for targets named SAXCount

# Build rule for target.
SAXCount: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SAXCount
.PHONY : SAXCount

# fast build rule for target.
SAXCount/fast:
	$(MAKE) $(MAKESILENT) -f _deps/xerces-c-build/samples/CMakeFiles/SAXCount.dir/build.make _deps/xerces-c-build/samples/CMakeFiles/SAXCount.dir/build
.PHONY : SAXCount/fast

#=============================================================================
# Target rules for targets named SAXPrint

# Build rule for target.
SAXPrint: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SAXPrint
.PHONY : SAXPrint

# fast build rule for target.
SAXPrint/fast:
	$(MAKE) $(MAKESILENT) -f _deps/xerces-c-build/samples/CMakeFiles/SAXPrint.dir/build.make _deps/xerces-c-build/samples/CMakeFiles/SAXPrint.dir/build
.PHONY : SAXPrint/fast

#=============================================================================
# Target rules for targets named SCMPrint

# Build rule for target.
SCMPrint: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SCMPrint
.PHONY : SCMPrint

# fast build rule for target.
SCMPrint/fast:
	$(MAKE) $(MAKESILENT) -f _deps/xerces-c-build/samples/CMakeFiles/SCMPrint.dir/build.make _deps/xerces-c-build/samples/CMakeFiles/SCMPrint.dir/build
.PHONY : SCMPrint/fast

#=============================================================================
# Target rules for targets named SEnumVal

# Build rule for target.
SEnumVal: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SEnumVal
.PHONY : SEnumVal

# fast build rule for target.
SEnumVal/fast:
	$(MAKE) $(MAKESILENT) -f _deps/xerces-c-build/samples/CMakeFiles/SEnumVal.dir/build.make _deps/xerces-c-build/samples/CMakeFiles/SEnumVal.dir/build
.PHONY : SEnumVal/fast

#=============================================================================
# Target rules for targets named StdInParse

# Build rule for target.
StdInParse: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 StdInParse
.PHONY : StdInParse

# fast build rule for target.
StdInParse/fast:
	$(MAKE) $(MAKESILENT) -f _deps/xerces-c-build/samples/CMakeFiles/StdInParse.dir/build.make _deps/xerces-c-build/samples/CMakeFiles/StdInParse.dir/build
.PHONY : StdInParse/fast

#=============================================================================
# Target rules for targets named XInclude

# Build rule for target.
XInclude: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 XInclude
.PHONY : XInclude

# fast build rule for target.
XInclude/fast:
	$(MAKE) $(MAKESILENT) -f _deps/xerces-c-build/samples/CMakeFiles/XInclude.dir/build.make _deps/xerces-c-build/samples/CMakeFiles/XInclude.dir/build
.PHONY : XInclude/fast

#=============================================================================
# Target rules for targets named gmock

# Build rule for target.
gmock: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock
.PHONY : gmock

# fast build rule for target.
gmock/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googlemock/CMakeFiles/gmock.dir/build.make _deps/googletest-build/googlemock/CMakeFiles/gmock.dir/build
.PHONY : gmock/fast

#=============================================================================
# Target rules for targets named gmock_main

# Build rule for target.
gmock_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock_main
.PHONY : gmock_main

# fast build rule for target.
gmock_main/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googlemock/CMakeFiles/gmock_main.dir/build.make _deps/googletest-build/googlemock/CMakeFiles/gmock_main.dir/build
.PHONY : gmock_main/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googletest/CMakeFiles/gtest.dir/build.make _deps/googletest-build/googletest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googletest/CMakeFiles/gtest_main.dir/build.make _deps/googletest-build/googletest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

#=============================================================================
# Target rules for targets named parser

# Build rule for target.
parser: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 parser
.PHONY : parser

# fast build rule for target.
parser/fast:
	$(MAKE) $(MAKESILENT) -f libraries/CMakeFiles/parser.dir/build.make libraries/CMakeFiles/parser.dir/build
.PHONY : parser/fast

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/XMR.dir/build.make CMakeFiles/XMR.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/XMR.dir/build.make CMakeFiles/XMR.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/XMR.dir/build.make CMakeFiles/XMR.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... doc-style"
	@echo "... doc-xml"
	@echo "... xerces-c-headers"
	@echo "... xerces-c-missing"
	@echo "... Char16Test"
	@echo "... CreateDOMDocument"
	@echo "... DOMCount"
	@echo "... DOMMemTest"
	@echo "... DOMPrint"
	@echo "... DOMTest"
	@echo "... DOMTraversalTest"
	@echo "... DOMTypeInfoTest"
	@echo "... EncodingTest"
	@echo "... EnumVal"
	@echo "... InitTermTest"
	@echo "... MemHandlerTest"
	@echo "... MemParse"
	@echo "... NetAccessorTest"
	@echo "... Normalizer"
	@echo "... PParse"
	@echo "... PSVIWriter"
	@echo "... RangeTest"
	@echo "... Redirect"
	@echo "... SAX2Count"
	@echo "... SAX2Print"
	@echo "... SAXCount"
	@echo "... SAXPrint"
	@echo "... SCMPrint"
	@echo "... SEnumVal"
	@echo "... StdInParse"
	@echo "... ThreadTest"
	@echo "... XInclude"
	@echo "... XMR"
	@echo "... XSTSHarness"
	@echo "... XSValueTest"
	@echo "... XSerializerTest"
	@echo "... gmock"
	@echo "... gmock_main"
	@echo "... gtest"
	@echo "... gtest_main"
	@echo "... parser"
	@echo "... xerces-c"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

